from typing import Sequence
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from src.core.base_repository import BaseRepository
from src.statements.models import Statement

class StatementRepository(BaseRepository[Statement]):
    def __init__(self, session: AsyncSession):
        super().__init__(Statement, session)

    async def get_by_investor_id(self, investor_id: int) -> Sequence[Statement]:
        """Fetch all statements generated by the investor."""
        result = await self.session.execute(
            select(Statement).where(Statement.investor_id == investor_id)
        )
        return result.scalars().all()
